# Calamares Partitioning Configuration for Conjunction Linux
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M

userSwapChoices:
  - none
  - small
  - suspend
  - file

drawPartitionLabels: true

defaultPartitionTableType: gpt
defaultFileSystemType: "btrfs"

btrfsSubvolumes:
  - mountPoint: /
    subvolume: /@
  - mountPoint: /home
    subvolume: /@home
  - mountPoint: /var/log
    subvolume: /@var_log
  - mountPoint: /var/cache/pacman/pkg
    subvolume: /@pkg

btrfsMountOptions:
  - subvol
  - compress=zstd
  - noatime
