[General]
DisplayServer=x11
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Autologin]
User=conjunction
Session=plasmax11.desktop
Relogin=false

[Theme]
Current=breeze
CursorTheme=breeze
CursorSize=24
EnableAvatarsThreshold=0

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true
