[Theme]
Current=conjunction
CursorTheme=breeze_cursors
CursorSize=24

[Wayland]
EnableHiDPI=true
SessionDir=/usr/share/wayland-sessions

[General]
InputMethod=
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true
