[workspace]
resolver = "2"
members = [
    "conjunction-core",
    "cj",
    "application",
    "app_sync",
    "conj-bundle",
    "conj-appd",
    "conj-appctl",
    "conj-open",
    "conj-sysd"
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
regex = "1.10"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
libc = "0.2"
